@Api_HostAddress = http://localhost:5264

###

GET {{Api_HostAddress}}/api/data

###

GET {{Api_HostAddress}}/api/data/81e31fb5-cc7a-44d0-b5d4-7aa49fccbe27
Accept: application/json

###

POST {{Api_HostAddress}}/api/data
Content-Type: application/json

{
    "DataValue": "somevalue"
}

###
PUT {{Api_HostAddress}}/api/data/2ea315bd-903e-4097-a872-81f33ed62435
Content-Type: application/json

{
    "DataValue" : "updated-somevalue"
}

###
DELETE {{Api_HostAddress}}/api/data/2ea315bd-903e-4097-a872-81f33ed62435
