# @Api_HostAddress = http://localhost:5264
@Api_HostAddress = http://localhost:8080

### GET ALL

GET {{Api_HostAddress}}/api/data

### GET BY ID

GET {{Api_HostAddress}}/api/data/a26a9c3e-c1df-41e7-93d5-d39c688e0097
Accept: application/json

### ADD

POST {{Api_HostAddress}}/api/data
Content-Type: application/json

{
    "DataValue": "somevalue"
}

### UPDATE

PUT {{Api_HostAddress}}/api/data/5a7f0ad3-66a0-4f14-8f29-d7d2119bdb3d
Content-Type: application/json

{
    "DataValue" : "updated-somevalue"
}

### DELETE

DELETE {{Api_HostAddress}}/api/data/5a7f0ad3-66a0-4f14-8f29-d7d2119bdb3d
